### ISSUE TITLE
node error

### ISSUE THREAD

**Issue by testbughub** [RonnyFalconeri/SmartPi#2]
I get this when trying to run "node webserver.js":
`internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'rpi-433'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/pi/SmartPi/webserver.js:7:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
`
I don't know anything about node, so I'm unsure what info to provide.

**Comment by testbughub** [comment]
I decided to revisit this, and found that I had to use rpi-433-v3 instead. 
Works fine now!
